### ISSUE TITLE
Web-interface

### ISSUE THREAD

**Issue by DeXP** [proninyaroslav/libretorrent#1]
I want to control my torrent-client via desktop browser. Usecase: Android TV-box as a server with torrent-client.
I want at least: add/remove/pause torrents. Control speed limits. Set per-file priorities.
Also it will be good to change visual style/theme: light and dark at least.

**Comment by DeXP** [comment]
tTorrent have a web-UI, but it's very simple and little functional. It uses NanoHTTPD as inline web-server:
https://github.com/NanoHttpd/nanohttpd

**Comment by proninyaroslav** [comment]
@DeXP 
I will look into this issue in the near future, since I combine work and study at the same time. I'll let you know as soon as begin work on this feature.

**Comment by DeXP** [comment]
@proninyaroslav 
I can help with web-part. But it will too difficult to me to integrate NanoHTTPD. 
To make a web-UI I will need API - URL adresses for each action.

**Comment by proninyaroslav** [comment]
@DeXP 
Ok, I'll work on the server-part.

**Comment by dessalines** [comment]
I don't see why a web interface is necessary. Generally people don't run web servers off their phones, and clients like `deluge` and `rtorrent` already have web interfaces.

**Comment by pjbarnoy** [comment]
@dessalines I'm pretty sure we're talking about a web client for LibreTorrent (as the server), to be accessed from other devices.

**Comment by deavmi** [comment]
I guess you could add this.

I don't really see the use in it though.

**Comment by DeXP** [comment]
@deavmi TV-boxes are perfectly silent, have small power consumption (mobile phones too!). You can turn-off your PC for a night time. And get all torrents downloaded by silent Android-device.

Web-UI is useful to control the torrent. For example, I need to find and choose good torrent to download. I prefer to do this on my comfortable PC. Then open tab in the browser and send .torrent-file to my device. Turn-off loud PC and go to sleep. At morning just copy downloaded files from Android to PC. In that case I do not see Android-UI at all! I just use my browser.

**Comment by dessalines** [comment]
At least in the meantime, I highly suggest just using `deluge-web`. Accessible through any web browser, or you can use clients like `transdrone` to control it from android. ![pic](https://s14-eu5.ixquick.com/cgi-bin/serveimage?url=http:%2F%2Fcdn.htpcbeginner.com%2Fimages%2F2012%2F05%2FDeluge-Web-Interface.png&sp=29807b0c60615ced0795b7116123cf2e).

**Comment by DeXP** [comment]
@dessalines 
Do you suggest to use Deluge instead of LibreTorrent? It is not possible, since there is no Deluge server for Android. You can control you remote torrent-client via Android device with Deluge. My task is reversed: Android device must be a server, who actually download files...

If you suggest to cut webui part from Deluge and use it in LibreTorrent - it is very hard too. Since LibreTorrent was written in Java, Deluge - in Python.

**Comment by dessalines** [comment]
Android isn't to the level yet where we should be relying on it for servers, especially web servers. Its mainly for phones and tablets, not dedicated web servers. I highly suggest just running a dedicated linux web server for this stuff. 

My setup at least, is a linux server that runs `deluge`, and `plex`, and a chromecast for my tvs and such. I'm seeding thousands of torrents, that's not exactly something I'd want an ARM device with limited ram to handle. That said, android torrenting is still useful if I just want to grab a video and watch it quick, or download some ebooks, or whatever.

**Comment by DeXP** [comment]
Dedicated Linux server is a good and right solution. But you must have that server. If apartments are small than PC is too loud.

Yep, Android torrenting is not for thousands of torrents. I use it only for night-time downloads. All data moving to PC at morning. After that seeding daytime only.

**Comment by deavmi** [comment]
I'd never use my phone really as a server. Just nah man. The hardware 
ain't made for that.

**Comment by deavmi** [comment]
I guess so. Then add it. :)

October 23, 2016 10:43 AM, "Dmitry Hrabrov"  wrote:
	@deavmi (https://github.com/deavmi) TV-boxes are perfectly silent, have small power consumption (mobile phones too!). You can turn-off your PC for a night time. And get all torrents downloaded by silent Android-device. 

	Web-UI is useful to control the torrent. For example, I need to find and choose good torrent to download. I prefer to do this on my comfortable PC. Then open tab in the browser and send .torrent-file to my device. Turn-off loud PC and go to sleep. At morning just copy downloaded files from Android to PC. In that case I do not see Android-UI at all! I just use my browser.

**Comment by deavmi** [comment]
Transdrone is cool. Deluge has a nice UI wow. I'd say better than 
Transmission's.

**Comment by deavmi** [comment]
Cooleo.
