### ISSUE TITLE
PIECES tab does not scroll properly

### ISSUE THREAD

**Issue by shadilaykekistan** [proninyaroslav/libretorrent#103]
https://streamable.com/kuwgx

When scrolling up and down on the pieces tab the page quickly scrolls back. It does this whether I scroll slowly or quickly. I cannot even access the bottom of the pieces tab. This only happens on the pieces tab, I have tried the other tabs and they do not exhibit this problem. I have tried with other torrents and it's still the same, only the pieces tab does not scroll properly. 

Installed from F-Droid
App version 1.4
Android version 7.0
Device is Moto G5 Plus

**Comment by proninyaroslav** [comment]
Hi. has long since been fixed https://github.com/proninyaroslav/libretorrent/commit/25ece06564e034f941e8fb6128c0caca239ddbe1. This patch will be included in the next release. If the problem persists, let me know.
