### ISSUE TITLE
LED indicator color resets to purple after shutdown and restart

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#105]
1) Change LED indicator color to something else, say white. Confirm with OK and go back to torrents page.
2) Shutdown Libretorrent
3) Start Libretorrent and go to appearance page. LED indicator is back to purple.

**Comment by proninyaroslav** [comment]
I could not reproduce this problem. Reset color to default appears only on the settings page?

**Comment by proninyaroslav** [comment]
Version 1.5 is out, in case of repeat this problem reopen the issue.
