### ISSUE TITLE
Add ability to make torrents from app.

### ISSUE THREAD

**Issue by xepheratu** [proninyaroslav/libretorrent#107]
As the title says, I believe the app would work much better for some peoples needs if it allowed people to make a torrent, copy the magnet link and send it to others. I personally use it to send large or many files to my fiance who currently lives far away from me. I dont want to rely on a third party handling my uploads so I want to use P2P.

**Comment by julienzz** [comment]
great idea, this way we don't have to use the PC or MAC for large file sharing.

**Comment by proninyaroslav** [comment]
Implemented.
