### ISSUE TITLE
Add adaptive icon

### ISSUE THREAD

**Issue by flipflop97** [proninyaroslav/libretorrent#108]
Android 8.0 now relies on [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) as primary app icons. Can this be added to the app so it will look less out of place?

**Comment by proninyaroslav** [comment]
Hello. What exactly do you want to see in the new icon? The possibility of changing the form (square, rounded square, circle, etc.)?

**Comment by flipflop97** [comment]
Yes, an adaptive icon is an additional icon that can take whatever shape it wants. So with one icon you have all possible shapes (the system decides which one is used).

**Comment by proninyaroslav** [comment]
Implemented.
