### ISSUE TITLE
Empty dialog when clicking "Add" from notification

### ISSUE THREAD

**Issue by AndhikaWB** [proninyaroslav/libretorrent#109]
![screenshot_2017-09-24-07-08-46](https://user-images.githubusercontent.com/17119394/30778118-40866cb4-a0f7-11e7-9ac6-0a87613936bf.png)

**Comment by proninyaroslav** [comment]
Hello. What Android version?

**Comment by AndhikaWB** [comment]
Sorry for the late reply. My Android is Lollipop 5.0 (SDK21), and it's not AOSP rom, but ASUS rom

**Comment by proninyaroslav** [comment]
I will test this on version 5.0. Perhaps this is a problem in your firmware.

**Comment by proninyaroslav** [comment]
I checked on version 5.1 and found no such error.

**Comment by AndhikaWB** [comment]
I appreciate your help, thanks for trying. It's not a big issue for me at all :)
