### ISSUE TITLE
Files that are not selected will also be downloaded

### ISSUE THREAD

**Issue by xeeoon** [proninyaroslav/libretorrent#111]
This is a great application, but i just find an issue.  Firstly, I add an magnet link and entered into the **DetailTorrentActivity** which contains **DetailTorrentFilesFragment**.  Here are the screenshots:
  Selecting the files i want to download:
![screenshot_20171017-001026](https://user-images.githubusercontent.com/24264034/31623087-eb72a5d0-b2d0-11e7-9154-665f143d0995.png)

Start downloading:
![screenshot_20171017-001037](https://user-images.githubusercontent.com/24264034/31623117-0aa91b5a-b2d1-11e7-98bd-57ec0be255e7.png)

A moments later:
![image](https://user-images.githubusercontent.com/24264034/31623210-52a43e94-b2d1-11e7-827e-630257839e85.png)
![image](https://user-images.githubusercontent.com/24264034/31623245-6b01a3fa-b2d1-11e7-8778-eea887329e71.png)

It just downloaded every files in the magnet, include files that i didn't select. Is there are any ways to fix this?  And sorry for my bad English, But i think you can understand what i mean. Thanks!

**Comment by proninyaroslav** [comment]
Hello. Please see this issue #106.

**Comment by xeeoon** [comment]
I tried to apply the changes in issue#106, but still it seemes nothing changed, 
  It downloaded the files I didn't select anyway...
And I built latest resources, which is v 1.4, has the same problem.
Then I tried v1.3 , everything works fine 😂😂

**Comment by proninyaroslav** [comment]
Could you send me a magnet link or a torrent file?

**Comment by xeeoon** [comment]
magnet:?xt=urn:btih:6b79260ab51b2b6d4f6fbd80d608f55de68d4234&dn=VA+-+Uplifting+Only+Top+15%3A+October+%282017%29+MP3+%5B320+kbps%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710
magnet:?xt=urn:btih:808a9ef99aec23b1d0fa218a0d70feb6bb0db34e&dn=Linkin+Park+-+Discography+%281997-2017%29+MP3+%5B96-320+kbps%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710

**Comment by xeeoon** [comment]
@proninyaroslav 
It is strange that this bug only happens with magnet link.
It I chose open file and download with torrent files, everything works fine! 
.

**Comment by proninyaroslav** [comment]
I repeated your actions and chose file number two. Only it downloaded. This is normal behaviour.

**Comment by xeeoon** [comment]
But.... Please see this video:
http://67.216.209.139/test.mp4
The files i selected are about 7MB , but it shows there are 9.08GB to download;

**Comment by proninyaroslav** [comment]
And in the Files tab they were all selected (after adding)? Or physically he downloaded one file, and showed that he downloaded everything?

**Comment by xeeoon** [comment]
After adding, they are "Ignore" ,  Physically downloaded everything.
You can see this longer video: http://67.216.209.139/test2.mp4
I tried V1.4  released on 8 Jul And the newest resource code, they have the same problem.
But if i open a torrent file instead of using magnet link to download, everything works fine, just like V1.3.

**Comment by xeeoon** [comment]
@proninyaroslav 
If the program crash and restarted, It shows normally.
About the Crash issue , it happens in very high dpi devices , most of the devices works fine . 
http://67.216.209.139/test4.mp4

**Comment by proninyaroslav** [comment]
Hi. I was able to reproduce the problem. Also it is accompanied by crash.

**Comment by proninyaroslav** [comment]
Fixed.
