### ISSUE TITLE
Add file association for .torrent files?

### ISSUE THREAD

**Issue by GitBoudewijn** [proninyaroslav/libretorrent#115]
If you have a .torrent file saved on your device and you try to open it from the file manager, it would be nice if you can select to open it with LibreTorrent. Is this possible?

**Comment by proninyaroslav** [comment]
The file association already exists. What file manager do you use? Perhaps your file manager does not support the association of torrent files.

**Comment by proninyaroslav** [comment]
Version 1.5 is out, in case of repeat this problem reopen the issue.
