### ISSUE TITLE
Can't install new release on Android 5.0.2

### ISSUE THREAD

**Issue by surferjoeit** [proninyaroslav/libretorrent#118]
Please see https://github.com/gateship-one/odyssey/issues/100, same problem with Libretorrent, i downloaded the apk and it force close to the file manager, so i can't install. It should be solved by upgrading build tools.

**Comment by proninyaroslav** [comment]
Hi. I didn't update build tools version because f-droid still doesn't support 27.0.0. I can update the version in the repository, can you build apk it yourself?

**Comment by surferjoeit** [comment]
Unfortunately no....
but other apps have been updated through F-Droid and now the problem is solved.

**Comment by proninyaroslav** [comment]
After about an hour I can build apk

**Comment by surferjoeit** [comment]
Thanks!

**Comment by proninyaroslav** [comment]
Build with Build Tools 27.0.1.
[app-release.zip](https://github.com/proninyaroslav/libretorrent/files/1510391/app-release.zip)

**Comment by surferjoeit** [comment]
I confirm that the issue is fixed... Many thanks!
