### ISSUE TITLE
Implement BEP 53 - Magnet URI extension - Select specific file indices for download

### ISSUE THREAD

**Issue by dessalines** [proninyaroslav/libretorrent#119]
http://www.bittorrent.org/beps/bep_0053.html

**Comment by proninyaroslav** [comment]
On this occasion you should contact with the developers of libtorrent https://github.com/arvidn/libtorrent

**Comment by dessalines** [comment]
It's a client implemented extension.

**Comment by proninyaroslav** [comment]
Any magnet link is parsed using `add_torrent_params::parse_magnet_uri`, which provides all API and information about the magnet. At the moment `BEP 53` is not implemented in `libtorrent` and in this case I will have to create my own implementation of the `libtorrent`-like parser. I think you should to open issue in https://github.com/arvidn/libtorrent, in case of refusal on their part you can open this issue again and I implement it on the client side.

**Comment by dessalines** [comment]
Okay cool, this issues' been created now:

https://github.com/arvidn/libtorrent/issues/2572

**Comment by proninyaroslav** [comment]
I see that your proposal is approved and already implemented, in the next release the `libtorrent` update will be available.

**Comment by proninyaroslav** [comment]
Implemented https://gitlab.com/proninyaroslav/libretorrent/issues/119.
