### ISSUE TITLE
Client is downloading unchecked files until you restart it

### ISSUE THREAD

**Issue by randseed** [proninyaroslav/libretorrent#120]
I add the torrent via magnet link, select just one file and tap confirm button.
Its progress is still 500 KB while the overall progress is about 14 MB for now. If you turn it off and on again (Libretorrent i mean), it downloads that single file as it should, i.e. ignoring unchecked files. I'm certain that there is something wrong, maybe with priorities. Can anyone reproduce?

I'm using the latest version of LibreTorrent from F-Droid, Android 7.1.2 (Lineage OS 14.1).

**Comment by proninyaroslav** [comment]
Fixed in the 1.5 version, f-droid will update in a few days.
