### ISSUE TITLE
Speed limit

### ISSUE THREAD

**Issue by vegetasama** [proninyaroslav/libretorrent#121]
Download speed limit doesn't work.

**Comment by proninyaroslav** [comment]
Hello. Can you provide a concrete example?

**Comment by PiwwowPants** [comment]
@vegetasama do you mean the global speed limit from Settings or the per-download speed limit set for each download?

If the former, you're probably right. It looks like setGlobalDownload/UploadSpeedLimit is never called by anything and when we apply settings from the SettingsPack, sp.download/uploadRateLimit() is never set.

**Comment by proninyaroslav** [comment]
@PiwwowPants thank you, it was applied only in `onTrayPreferenceChanged` method, apparently I forgot to add this to the code that restores the session settings. Commit with fix: 15c1ca5.
