### ISSUE TITLE
Seeding Time is reset after shutdown

### ISSUE THREAD

**Issue by gheoan** [proninyaroslav/libretorrent#122]
Some BitTorrent servers recommend that clients seed a torrent for a specified duration. Total seed time can't be tracked in LibreTorrent because it is reset to 0 after application shutdown.

**Comment by proninyaroslav** [comment]
Hi. This is an old problem, I'm think fix it for the next release. Please see https://github.com/frostwire/frostwire-jlibtorrent/issues/130

**Comment by proninyaroslav** [comment]
Fixed  ad92e7e.

**Comment by gheoan** [comment]
Thanks!
