### ISSUE TITLE
peer block subscriptions

### ISSUE THREAD

**Issue by graingert** [proninyaroslav/libretorrent#125]
eg be able to enter a list of URLs or eMule dat and PeerGuardian databases. block the union of their ip addresses.

Will need to cache the contents and configure cache expiry

**Comment by proninyaroslav** [comment]
Hi. That is the ability to manually add IP addresses?

**Comment by graingert** [comment]
@proninyaroslav no, the opposite. Instead of a file, I'd like to be able to add a set of URLs, eg:

http://list.iblocklist.com/?list=cwworuawihqvocglcoss&fileformat=p2p&archiveformat=gz
http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz

I'd also like to be able to set custom headers such as `Referer: http://list.iblocklist.com` and `Authorization: Basic ...==`

**Comment by graingert** [comment]
that way libretorrent can download and update the blocklists automatically

**Comment by proninyaroslav** [comment]
Good idea, ok.

**Comment by graingert** [comment]
@proninyaroslav also can you support the p2p format, because you have to pay for .dat
