### ISSUE TITLE
allow 'Maximum active uploads' to be set to 0

### ISSUE THREAD

**Issue by graingert** [proninyaroslav/libretorrent#126]
meaning literally 0, not unlimited.

**Comment by graingert** [comment]
use `Double.POSITIVE_INFINITY;` for unlimited active uploads.

**Comment by proninyaroslav** [comment]
In `libtorrent` -1 or 0 means unlimited. In this case -1. I think it is necessary to think up something like a checkbox specifically for unlimited value.

**Comment by proninyaroslav** [comment]
So far you can set a large number.

**Comment by graingert** [comment]
But I don't want any active uploads

**Comment by proninyaroslav** [comment]
I know. I talked about the unlimited value.

**Comment by proninyaroslav** [comment]
Fixed f999b24.
