### ISSUE TITLE
Network Status Error

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [proninyaroslav/libretorrent#127]
Even Any Cellular Data Or WiFi Available. This Apps Notification Showing Always As "ONLINE"

**Comment by PiwwowPants** [comment]
I'm looking into this and have this pull request out for it already https://github.com/proninyaroslav/libretorrent/pull/130

I'm not convinced what "isListening" is in the app. It seems this notification should be telling the user that the client is ready to download, which would mean it is on wifi or cellular. Currently the check is just always returning true from the library used.
