### ISSUE TITLE
Following Google Style guideline 

### ISSUE THREAD

**Issue by hangduykhiem** [proninyaroslav/libretorrent#13]
Hey, I want to contribute to the project, but there is one thing on the README.md file that is a bit weird to me:

> Try to follow our coding style and formatting before submitting a patch.

Can we follow some predefined style guide, such as [Google's?](https://github.com/HPI-Information-Systems/Metanome/wiki/Installing-the-google-styleguide-settings-in-intellij-and-eclipse) It would help increase coding speed immensely.

**Comment by proninyaroslav** [comment]
Hello. I tried to follow the style of coding from Google, so you can use it.
