### ISSUE TITLE
Pressing search from the menuOptions then pressing the up button causes the search button to stay hidden

### ISSUE THREAD

**Issue by PiwwowPants** [proninyaroslav/libretorrent#132]
When the search button is pressed on the main-fragment, a search button appears in the option menu.
Pressing the search button in the options menu then pressing the up button in the fragment causes the search interface to close but not set the search button's visibility back to visible

Additionally, pressing this search button in the options menu hides itself without performing further actions.

**Comment by PiwwowPants** [comment]
Modifying the search item in main.xml to remove `collapsibleActionView` from the `showAsAction` attribute resolves this, since the search action won't collapse into the options menu when it is opened. The search action does seem to not work in the options menu though, which makes sense since it is missing from `onOptionsItemSelected`.  This fix would require adding functionality to the option when it's in the option menu.

Removing this attribute value though removes the up button from the searchView when it is opened, instead keeping the spinner in place. This may be seen as a benefit because you can switch between modes WHILE searching instead of having to close out to switch.

**Comment by proninyaroslav** [comment]
I think this is not critical, you can delete this attribute.

**Comment by PiwwowPants** [comment]
Gotchya. I agree. I think the odds of it ever coming up as an issue where that action button needs to collapse is slim. Removing it for now to potentially never have to re-add the functionality avoids a confusing bug.

Put in the pull request https://github.com/proninyaroslav/libretorrent/pull/146
