### ISSUE TITLE
Add An Option to Close WiFi State Automatically

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#135]
Along With Shut Down The App After Download Add An Option That Automatically Turn Off The WiFi Or Cellular Data . This Will Be Helpful For Users To Reduce Their Data Usage . In Order To Difficulties In Adding Scheduled Download option This Feature May Be Helpful.

**Comment by proninyaroslav** [comment]
The maximum that a third-party application can do without root - enable/disable wi-fi. And then only if the user has disabled tethering or Airplane Mode. So it will not always work.

**Comment by Jithendra-V-Kumar** [comment]
But Without Any Root Permission Apps Like ADM And Flud Etc Have The Ability To close The Cellular Data After Download Completion.

**Comment by proninyaroslav** [comment]
You can read about it here https://www.reddit.com/r/Android/comments/2oesvn/did_you_know_you_can_no_longer_disableenable_data/

**Comment by PiwwowPants** [comment]
I implemented this on my own build and it seems pretty useless without a rooted device. Under the perfect conditions @proninyaroslav mentioned, wifi will disable, but we have no way to touch cellular data or airplane mode without root access of the new MODIFY_PHONE_STATE check. I believe it was created in Android L, so *maybe* Flud can do it on a device running KitKat or lower, but it'd be frivolous to implement this for an OS that old.

If there is a reason to try to touch Wifi state on completion, I can push the branch, but right now, it's just an extra setting in the way that I feel no one will use.

**Comment by proninyaroslav** [comment]
@PiwwowPants I think it's too much control your phone from app.

**Comment by PiwwowPants** [comment]
I agree, I would like to avoid the settings section becoming a full automation suite for your phone. I'm sure there are super-users out there using Android devices as full-fledged torrent clients, but I'd like to continue to assume that most people are still using their phones as personal devices that they control on their own. It'd be very bad UX for a user to lose Wi-Fi connection because the app completed download.

**Comment by mlda065** [comment]
It's not libretorrent's responsibility to stop other apps from using consuming data. I think disabling the whole phone's wifi connection is outside of the scope of a torrenting app. 

There's already an option to shutdown the app when downloads complete, to stop this app from using more data than it has to. I think that's sufficient.

**Comment by IamJithendra** [comment]
I Preferred this option When People who Is Started  Downloading Torrents At Night And Goes For Sleep.Then Automatically Close WiFi After The Download Has Completed which will help the users to prevent Battery Drain and Data Loss
