### ISSUE TITLE
A Major Problem That Downloaded List Is Empty

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#138]
I Have Downloaded Some Files With This Torrent App And I Have Turned On The Auto Move After Download Option .
I Can't See The Downloaded List 

It Is Showing As Empty

**Comment by proninyaroslav** [comment]
I could not repeat your problem. Can you provide more information and screenshots?

**Comment by proninyaroslav** [comment]
Version 1.6 is released. If the error repeats let me know.
