### ISSUE TITLE
[Feature Request] Allow users to add infohashes to "add link" function

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#143]
A lot of clients such as qBittorrent have this feature. Basically, the client uses the entered infohash to search the DHT network the same way as adding a magnet link but without the extra characters for making a clickable browser link. 

Sometimes when searching for a file you can only find the infohash and turning it into a magnet link on a phone can be cumbersome so if we can just enter the raw infohash into the "add link" function, that would be great.

**Comment by rabbitsmith** [comment]
I would like to have this feature added to libretorrent. Seems much useful.

**Comment by proninyaroslav** [comment]
Good feature, ok. I have to see if it's possible to implement it.

**Comment by PiwwowPants** [comment]
I put in a pull request for this here https://github.com/proninyaroslav/libretorrent/pull/148. It will only validate with the BitTorrent protocol (btih:). If there is reason to support other protocols (sha1:), it'd have to be reworked but I assume we just support the BitTorrent protocol / the others are too niche.
