### ISSUE TITLE
Add libretorrent to comparison page

### ISSUE THREAD

**Issue by pataquets** [proninyaroslav/libretorrent#153]
See https://github.com/BiglySoftware/BiglyBT-Android/issues/31

**Comment by proninyaroslav** [comment]
It may be useful for peoples, but this app is not someone's competitor, it just gives the user freedom. Thank you.

**Comment by pataquets** [comment]
@proninyaroslav : It's not meant to compete, the intent was to give still more visibility to the project. And that's good for every FLOSS project around, isn't it?
Even giving awareness of more than one FLOSS project in some area might attract more devs in both directions, and even cross-pollinate work and features, IMHO.
Disclaimer: Using Libretorrent myself, so more LT visibility and awareness is better for me.
My intention was not to promote competition. Just enabling more cooperation. Sorry if I did not made my intention clear.
How does it sounds to you?

**Comment by proninyaroslav** [comment]
@pataquets I don't mind that more people will find out about LibreTorrent :). So you have the right to disseminate information about LibreTorrent in any sources, it's only welcomed.
