### ISSUE TITLE
Add BiglyBT's Swarm Discovery feature

### ISSUE THREAD

**Issue by pataquets** [proninyaroslav/libretorrent#154]
See https://github.com/BiglySoftware/BiglyBT/wiki/Swarm-Discoveries
Ideally, either on a compatible implementation or as some sort of agreed, standard protocol implementation.

**Comment by proninyaroslav** [comment]
This is not a feature of `BiglyBT`, it originally appeared in `Vuze`. Perhaps I will add this, I need to get acquainted with this in more detail and assess the adequacy of its implementation.

**Comment by pataquets** [comment]
Nice to know. Thanks for considering, @proninyaroslav.
