### ISSUE TITLE
Display per-file & per-torrent availability ratio

### ISSUE THREAD

**Issue by superbonaci** [proninyaroslav/libretorrent#155]
Would like to see what the availability is for each torrent and for all files inside each torrent:

![qBittorrent availability for files and torrents](http://oi67.tinypic.com/t8kcgz.jpg)

**Comment by proninyaroslav** [comment]
I added availability for all files, but not for each file:

![screenshot_1516787948](https://user-images.githubusercontent.com/7840559/35326225-0c1328d0-0107-11e8-8c51-f6085eab31ef.png)

Is availability necessary for each file?

**Comment by superbonaci** [comment]
@proninyaroslav yes it's neccesary because it's the only way to know which file is not complete. Without the option, I have to wait for the entire torrent to download to check.

If you want a money donation to help you, please tell me.

**Comment by proninyaroslav** [comment]
Ok, I will think how to make it less expensive procedure. About donation: I'm not particularly worried about this, at the moment it's more important for me to take into account all the wishes of users and implement them. Maybe I'll add information about the donate to README, then I'll let you know.

**Comment by proninyaroslav** [comment]
@superbonaci Added 554c514. About donation see README file, thank you.

![screenshot_1517158105](https://user-images.githubusercontent.com/7840559/35485098-55a665c2-046b-11e8-828e-51a8a3cc41cb.png)

**Comment by superbonaci** [comment]
Thanks. Are you going to upload the updated program to Google Play or F-Droid, or do I have to compile the apk myself?

P.S. made you a donation already.

**Comment by proninyaroslav** [comment]
@superbonaci many thanks for donate. Release will be in the next couple of days.
