### ISSUE TITLE
Sometimes The App Closes Automatically 

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [proninyaroslav/libretorrent#156]
When Any Torrents Are Downloading This App Closes Automatically and Thereafter The File Downloaded Size Shows From 0 and The Active a Time Also Starting From 0.

But The % That The File Downloaded Shows Accurate And Which Is Fine.

**Comment by proninyaroslav** [comment]
Can you provide a screenshot of this torrent? Active and seeding time have been fixed https://github.com/proninyaroslav/libretorrent/issues/122

**Comment by proninyaroslav** [comment]
Version 1.6 is released. If the error repeats let me know.
