### ISSUE TITLE
Some Changes To Notification Request

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#159]
The Function Of the Notification Used On The Apps Are To Prevent the App That Being Closed By  the 
System 

But There Is No Need Of Notofications When There No Torrents Are Downloading

Which Will Reduce The Apps Ram And Battery Usage

Please Do A Change to Show The Notification Only If Any Torrents 
Are Downloading

**Comment by proninyaroslav** [comment]
You can use `Keep alive` option in 1.6 version. It closes background service after closing the window Thank you.

**Comment by Jithendra-V-Kumar** [comment]
I Don't Mean This .I Am Not Telling About Keep alive Method

This App Starts Showing All the Time The App Is Launched

I Requested to Show the Notification  Only When Downloading Is Ongoing

**Comment by proninyaroslav** [comment]
App  will not work correctly if the server is turned off even if there are no downloads.

**Comment by Jithendra-V-Kumar** [comment]
I Don't Mean This .I Am Not Telling About Keep alive Method

This App Starts Showing All the Time The App Is Launched

I Requested to Show the Notification Only When Downloading Is Ongoing

When using  " Keep alive " when closing the app The App Also Closes the Background Service

Then The Downloading Stops.

The Idea That I Try To Explain Is Don't Show Notification When Launching the App 

When Any Downloading Starts Show The Notification And Start The Background Service And Close The Background Service When Download Finished.

**Comment by proninyaroslav** [comment]
I like this idea, but it will require dividing the service into two parts. I need to see if I can do it safely.
