### ISSUE TITLE
An Error On The Notification

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#160]
When Opens The App It Shows Foreground Notification and it Contains 
Pause / Resume and Shut Down Buttons

On Launching The Button On Notification Is Showing Pause But No Downloads Were Going On

On Click It Changes To Resume And Needs To Click Once Again This Button In Order
To Start Download

**Comment by proninyaroslav** [comment]
This is a forced inconvenience, because the app does not take responsibility and does not track paused or resumes torrents. It might be worth name this button as the 'pause/resume' button, but it looks cumbersome.
