### ISSUE TITLE
Notification Actions

### ISSUE THREAD

**Issue by GeoZac** [proninyaroslav/libretorrent#162]
App Version: 1.6
It would be helpful if an option **'Pause/resume torrents' and 'Add torrents'** is added to _Settings > Foreground notification_ ,which can help user to add torrent from Notification panel itself and also retains the pause /resume actions

**Comment by proninyaroslav** [comment]
Hello. You propose make it possible to add two buttons at once?

**Comment by GeoZac** [comment]
@proninyaroslav yes

**Comment by proninyaroslav** [comment]
As far as I can remember, I could not place them, there is not enough free space. I will try again.

**Comment by GeoZac** [comment]
If it was because of space constraints, no need to add.I use the highest dpi, so my mistake.
Issue may be closed
