### ISSUE TITLE
Needs An Update With New Features

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#167]
The Last Update We Got is About More than 2 Months Ago and Now Requests An Update With Some New Features

**Comment by kutsan** [comment]
I think it would be more helpful if you state what kind of new features do you want to see.

**Comment by IamJithendra** [comment]
make the Notifications Show Only When Files Are Downloading

Make it Possible to Turn Off WiFi after Download Complete

Try To Add Scheduled Downloading  

Rss Feed Subscribing Option


Any Of The above Features Will Be Helpful and Appreciated

**Comment by IamJithendra** [comment]
@proninyaroslav  Is the Build Deprecated ?

**Comment by proninyaroslav** [comment]
I think I will release app with the current fixes, since I was not able to complete fully support of external storage by this time, because in part this depends on the error in `jlibtorrent`. On the implementation of other issues, I still don't have time, since I'm writing a diploma.
