### ISSUE TITLE
Pausing/resuming torrent on program does not reflect on notification

### ISSUE THREAD

**Issue by superbonaci** [proninyaroslav/libretorrent#168]
If I pause or resume a torrent in the main window, the notification keep displaying "PAUSE/RESUME SHUTDOWN", only changes if I use the notification itself to change the download state.

**Comment by proninyaroslav** [comment]
This is normal, because the notification can not know if it's the only torrent on your list.

**Comment by superbonaci** [comment]
Ok thanks. Then at least show PAUSE ALL or RESUME ALL to be clearer.
