### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [proninyaroslav/libretorrent#170]
Please add support for icon shape
https://material.io/guidelines/style/icons.html

**Comment by proninyaroslav** [comment]
Icon shape works correctly
![screenshot_trebuchet_20180420-122012](https://user-images.githubusercontent.com/7840559/39043336-d9a6d6c6-4495-11e8-96fc-91486ed0448d.png)

**Comment by c-e-p-x-u-o** [comment]
My fault! Sorry!
