### ISSUE TITLE
Closes silently and downloads stop

### ISSUE THREAD

**Issue by adjenks** [proninyaroslav/libretorrent#172]
I'm using android 8.0.0
After a while, maybe 45 minutes, I notice that LibreTorrent is no longer in my notification menu. 
I open it up again and the downloads are all "checking".
I thoughy perhaps it was due to my phone trying to save power by managing background data usage or something, so I disabled any restraints to LibreTorrent in my application settings. It still seems to close randomly however. Any suggestions?

**Comment by proninyaroslav** [comment]
Hi. Android doesn't give any guarantees that the background process will be alive for a long time. This is unlikely for a process that has a foreground notification (in the case of LibreTorrent), but there is little chance that system will kill it if system have very small RAM at this time. 
To exclude bug in LibreTorrent, you need to write the log file during LibreTorrent is running. If you have the desire and the opportunity, download [Logcat Reader](https://github.com/darshanparajuli/LogcatReader) app (this is free software under MIT license), run it in the background and after LibreTorrent crashes, save the log and put it in this issue as a file.

**Comment by proninyaroslav** [comment]
I can not say until I see a log with an error that leads to closing.
