### ISSUE TITLE
Why can't the magnetic analysis in China, the torrent file download can not download?

### ISSUE THREAD

**Issue by 742340082** [proninyaroslav/libretorrent#173]
magnet:?xt=urn:btih:a5d5a89c478817ed311a0fe3de68379c5aa54014
magnet:?xt=urn:btih:a5d5a89c478817ed311a0fe3de68379c5aa54014
You can try this magnetic force

**Comment by proninyaroslav** [comment]
This magnet is downloading, I think the problem is in the blocking in your country.
