### ISSUE TITLE
ability to hide hidden files

### ISSUE THREAD

**Issue by r9guy** [proninyaroslav/libretorrent#177]
It is very annoying then im trying to move downloads in progress from Download Folder to Movies folder because i have to scroll throug androids system hidden files and folders to navigate to the one i need. Its because then chanching the download location browser is showing all folders. Plese add ability to hide hidden folders.  On android there are also folders starting with . dot simbol which os treats as hidden.

**Comment by proninyaroslav** [comment]
Ok.

**Comment by proninyaroslav** [comment]
For issues please visit https://gitlab.com/proninyaroslav/libretorrent. This repo is read-only mirror.
