### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by sguinetti** [proninyaroslav/libretorrent#19]
Por example, the open source Peerflix engine, usted in Turkey Torrent Player. Thanks.

Info: http://www.webupd8.org/2014/03/peerflix-stream-torrents-with-vlc-or.html

**Comment by thermatk** [comment]
Actually, this one should be easy to do. All streaming torrent players for Android are based on libtorrent 👍

**Comment by sguinetti** [comment]
Plus. This streaming support is good for TV screens and external players. DNLA is ok? Chromecast or WiFi direct?

**Comment by Nikitenko** [comment]
Any updates?
Streaming playing can be one of the main features.

**Comment by proninyaroslav** [comment]
@Nikitenko 
For starters I need to fix critical bugs and add primary features, such as support external storage. Any help is appreciated.
