### ISSUE TITLE
Download torrents Wi-Fi only

### ISSUE THREAD

**Issue by proninyaroslav** [proninyaroslav/libretorrent#20]

**Comment by lmao-emerald** [comment]
Any plans into doing this? Looks like a basic feature to me.

**Comment by proninyaroslav** [comment]
@lmao-emerald 
I might add this feature, but there are some problems with Android 7. Starting with this version, the system doesn't send notification in app about change Wi-Fi state, This is due to a decrease in energy consumption, as this function is energy intensive ([see Project Svelte](https://developer.android.com/about/versions/nougat/android-7.0-changes.html?#perf)). I can add tracking network status in the app, but it will be a negative impact on power consumption.

**Comment by proninyaroslav** [comment]
Added.
