### ISSUE TITLE
Incorrectly determines the size of free space

### ISSUE THREAD

**Issue by Sonic1234678** [proninyaroslav/libretorrent#26]
Incorrectly determines the size of free space, both on the internal sd-card and on the external sd. It shows a negative amount of free space, and therefore does not allow to add torrent.

Application Version 1.0 (Google Play)
Version Android 4.1.1 (kernel version 3.0.36)
Platform CityNight D8 (Chuwi V88 clone) (ARMv7, RockChip RK3188)

**Comment by proninyaroslav** [comment]
Hello. Can you write paths to the folders that you are trying to use?

**Comment by Sonic1234678** [comment]
It was folders "/mnt/sdcard/Download" and "/mnt/external_sd/Download/Torrent"

**Comment by proninyaroslav** [comment]
To estimate free space I use the standard tools of Android. It looks a bit strange. 
I need access to the device, so I suggest you put a special debug version, which I will do for this purpose.

**Comment by Sonic1234678** [comment]
Ok, where can I get this special debug version of the application?

**Comment by proninyaroslav** [comment]
You know how to use adb?

**Comment by Sonic1234678** [comment]
No

**Comment by proninyaroslav** [comment]
Ok. I will consider it. Leave your e-mail, I'll send you APK in the next few days

**Comment by Sonic1234678** [comment]
Ok, my e-mail: zCyberPunkz at gmail dot com

**Comment by proninyaroslav** [comment]
See issue #33 . I sent APK you from e-mail.

**Comment by Sonic1234678** [comment]
I have installed and tested the version you sent me, it works fine. Thank you!
