### ISSUE TITLE
Notificate if the file does not download in x seconds

### ISSUE THREAD

**Issue by sguinetti** [proninyaroslav/libretorrent#27]
For example, the file starts in 0. In 20 seconds this file is not downloading. Automatically, pause the file and display a notification suggests that try it later.

**Comment by proninyaroslav** [comment]
i.e. notify user if download does not start within a certain time?

**Comment by sguinetti** [comment]
Right. To find a problem of the torrent file (seed o another) but not a bug from the app.

**Comment by proninyaroslav** [comment]
The wording of this function is too vague, since the time when seeds are found is very different. You will have to select this value by experience, this is not good. You can suggest something more specific on this issue, for the time being I close the issue.
