### ISSUE TITLE
Random port feature does not actually randomize but goes up sequentially 

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#30]
I've noticed that the random port feature doesn't actually randomly select a port upon initializing LibreTorrent. It only goes sequentially. 

For example, if you turn off the "random port" setting and manually type in port 10000 and then turn on the "random port" setting, the next shutdown and restart will give you a "random" port of 10001. Another shutdown and restart gives you 10002. Another shutdown and restart gives you 10003. And so forth. 

Can we actually have the port be selected at random with a random number generator?

**Comment by hangduykhiem** [comment]
I have notice this, in my PR and in issue #8 . I can work on this.

**Comment by Cormak** [comment]
Thank you, @hangduykhiem

**Comment by proninyaroslav** [comment]
Initially, I put a different meaning to this function. And I did not conceive it as a random, but it would be nice to add thisю
