### ISSUE TITLE
Please add "maximum peers per torrent" and "maximum upload slots per torrent" to limitations

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#31]
I've noticed that we don't have "maximum peers per torrent" and "maximum upload slots per torrent" settings in the global "Limitations" settings page. 

Can we have these settings so we can further limit how many peers a single leeching torrent can connect to, as well as limit how many peers a seeding torrent can upload to?

All major torrent clients have these settings and it would be great for us to have them, too.

**Comment by proninyaroslav** [comment]
Added.
