### ISSUE TITLE
SD card / ext storage free space reported incorrectly on some handsets

### ISSUE THREAD

**Issue by bitmansofthu** [proninyaroslav/libretorrent#33]
Hi,
The getFreeSpace() method returns a negative/incorrect value on some handsets (Sony Xperia E 4.1.1 / HTC Desire (custom 4.1 ROM)), and the app didn't allow to start the torrent.
I have modified this function on a forked branch to use File.getUsableSpace(), which seems to report the free space correctly:
https://github.com/bitmansofthu/libretorrent/commit/c591e1e9c1b07625583bc4293a091d2c5843cd67

**Comment by proninyaroslav** [comment]
Hello. I'll check it tomorrow. if everything is correct you will be able to do pull request?

**Comment by bitmansofthu** [comment]
I have created, please ignore the commit with the version bump is possible.

**Comment by proninyaroslav** [comment]
Thank for bugfix!
