### ISSUE TITLE
Ability to pause torrent after downloading

### ISSUE THREAD

**Issue by proninyaroslav** [proninyaroslav/libretorrent#37]
E.g, once a torrent downloaded, it will continue to seed for 5 minutes and then it will pause. User can adjust the amount of required time.

**Comment by dessalines** [comment]
Shouldn't the libtorrent [auto-manager](http://www.libtorrent.org/manual-ref.html) handle this? Its not a good idea to manually pause torrents, but instead set a `maxActive`, and let the auto-manager discover which torrents need seeders.

**Comment by proninyaroslav** [comment]
The idea looks like a shit, if this function is anyone needs please open this issue again.

**Comment by graingert** [comment]
@proninyaroslav I really use this feature a lot in Flud.

**Comment by proninyaroslav** [comment]
@graingert you can use `Maximum active uploads` option in `Limitations` settings.

**Comment by graingert** [comment]
@proninyaroslav it won't let me go below 1 though.

**Comment by graingert** [comment]
@proninyaroslav https://github.com/proninyaroslav/libretorrent/issues/126
