### ISSUE TITLE
Downloading always stops every several seconds

### ISSUE THREAD

**Issue by teod0r** [proninyaroslav/libretorrent#39]
I tryed to download magnet:?xt=urn:btih:XL52WI4KMU6ARE6OZWOJSKSVTDKCPH5P.
Downloading always stops every several seconds, and I have to manualy resume it.

**Comment by proninyaroslav** [comment]
Hello. For test, I downloaded 10% torrent in the background and didn't notice any problems. It happens to all torrents? How many your RAM in phone?

**Comment by teod0r** [comment]
It is the first torrent that I tryed.
By the way I tryed to download the only one largest .mp4 file.
My tablet has 1.5Gb RAM.

**Comment by proninyaroslav** [comment]
Try to download this torrent again and watch the Internet connection and memory consumption. 
Also, try to download any torrent more.

**Comment by hangduykhiem** [comment]
It would be very helpful to have your tablet model too. Thanks.

**Comment by teod0r** [comment]
My tablet is samsung Galaxy TAB4 10.1. I use cyanogenmod 11.
I tryed to download this torrent again and memory consumption is normal. There is a lot of memory left. Internet connection is present.
Also I tryed to view logcat, and there is nothing between non-paused and paused states of the torrent, it just pauses suddenly.
I'll try another tottents latly.

**Comment by Azaradel** [comment]
Be sure you have allowed working in background in baterry management. Probably your problem is caused by system trying to save energy

**Comment by teod0r** [comment]
Option "Keep CPU awake" is on

**Comment by hiseni** [comment]
Hey, guys! Same happening for me too. Very time I try to download anything - it starts great, turn speed drop to 0 in seconds. Same torrent works well with rTorrent app. I use BQ M10 tablet.

**Comment by proninyaroslav** [comment]
Now I transfer app to jlibtorrent 1.2.x, so you should check it out after the transfer.

**Comment by teod0r** [comment]
I tryed another torrent http://torrent-filmi.net/uploads/torrent/2016-10/tvlend.net-the-nice-guys-647077.torrent and it doesn't stop, but the program crashed 4 times while downloading

**Comment by proninyaroslav** [comment]
@teod0r 
Please install this version https://proninyaroslav.ru/ftp/app-release.apk (it's a current master branch, updated to jlibtorrent 1.2.x).

**Comment by tmihai20** [comment]
Please push the update to Play Store, this issue was the only one preventing me to use this app.

**Comment by proninyaroslav** [comment]
I do this for a couple of days after sorting will be done.

**Comment by proninyaroslav** [comment]
If this problem appears again, let me know.

**Comment by diegosilberg** [comment]
The problem persists, i can not download anything, it stops after a few seconds

**Comment by proninyaroslav** [comment]
@diegosilberg
Is your problem similar to this one https://github.com/proninyaroslav/libretorrent/issues/93 ?
