### ISSUE TITLE
Please remove Tor support.

### ISSUE THREAD

**Issue by skorokithakis** [proninyaroslav/libretorrent#4]
Torrenting over Tor uses too many resources for no benefit, and is very detrimental to the Tor network, while slowing down downloads and not providing enough anonymity.

Please remove this feature for the good of the Tor network.

**Comment by Overv** [comment]
I also can't imagine why anyone would want to do it with the abysmal speeds.

**Comment by mateoeh** [comment]
Some more info:
https://www.torproject.org/docs/faq.html.en#FileSharing
https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea

**Comment by pjbarnoy** [comment]
Maybe make it a build option so those who really truly want the feature can still have it, but remove it from prebuilt version.

**Comment by proninyaroslav** [comment]
Hello. I understand that it's most likely an ethical question, but there are cases where access to the Tor is needed. So I make this function separately if you don't want to use Tor, you can't enable function.

**Comment by proninyaroslav** [comment]
Ok, I didn't expect such a reactive criticism towards Tor, so I have to remove it in the near release.

**Comment by skorokithakis** [comment]
@proninyaroslav, you are right, but the problem is that many more people would use it "just in case" than would actually need it, and the detriment to the network would be too big 🙁

Thanks for understanding, and for your effort, your client has already replaced tTorrent for me!

**Comment by DamonGant** [comment]
Torrents are one of the reasons I eventually took down an exit I ran. Eventually you just don't want to deal with the daily copyright notices any more, so thanks for removing it.

**Comment by martinrotter** [comment]
So, you users ask developer to remove the feature which can be abused by ROOKIE users? Why removing it? This is pure non-sense.

Maybe, just adding some kind of super-warning message-box when using torrentz-over-tor would and should be enough.

I really just do not understand why anyone should remove a working feature from a SW just because some idiotic users might get it wrong and abuse it.

**Comment by skorokithakis** [comment]
It's because some idiotic users might get it wrong and abuse it. Abuse is bad, especially for Tor, which can't really take it.

**Comment by proninyaroslav** [comment]
@martinrotter 
This problem is really complicated, and it would be better if I delete it. Orbot can mask traffic of any program, so those who want Tor, don't lose practically nothing.

**Comment by DamonGant** [comment]
@martinrotter It's not so much an issue that users don't understand the implications of Torrent over Tor, it's just that torrenting over Tor is a colossal waste of bandwidth, Tor has enough load as it is and most importantly you're taking a huge dump on exit operators who have to deal with the fallout of your torrenting.
