### ISSUE TITLE
Tap to open files

### ISSUE THREAD

**Issue by anoadragon453** [proninyaroslav/libretorrent#43]
Should be fairly straightforward. Opening files by tapping on them in the 'Files' column would save the user from having to navigate to it through their file manager.

**Comment by proninyaroslav** [comment]
Hello. Tap to open file is already implemented (in 1.0 version).

**Comment by Gheoan** [comment]
Should this issue be closed?

**Comment by anoadragon453** [comment]
Yeah, tap to open files works, albeit with a small time delay.
