### ISSUE TITLE
App uses a lot of battery power.

### ISSUE THREAD

**Issue by noughtmare** [proninyaroslav/libretorrent#46]
I don't know what might cause this, but my phone uses a lot more battery when libretorrent is running in the background (with only 2 torrents seeding). Other android torrent clients like flud don't have this problem.

I am using the fdroid version 1.1 on a Nexus 4 with CM 13 installed.

**Comment by proninyaroslav** [comment]
Hello. This app quite young and needs some work, so this issue will be resolved in the future.

**Comment by proninyaroslav** [comment]
Recent observations led me to the conclusion that reason for the large battery consumption is the application's interaction with network. I will think about how to optimize battery consumption.
