### ISSUE TITLE
Save to external storage

### ISSUE THREAD

**Issue by pjbarnoy** [proninyaroslav/libretorrent#5]
Trying to change the torrent save location to a folder on the SD card currently gives "Error: Unable to use selected folder to download. Please select another folder"

App Version: 1.0 from Google Play
Device: SM-G935T 6.0.1

**Comment by proninyaroslav** [comment]
Hello. This problem begins with version 4.4, because Google make complicated access to secondary storage. I will try to make the secondary storage support this week, this is not an easy task.

**Comment by proninyaroslav** [comment]
I think can be use POSIX wrapper for libtorrent (see Frostwire example https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/AndroidPlatform.java#L127).

**Comment by coolamz** [comment]
How to apply it? Can you please tell step by step? Also, you can check Flud torrent https://play.google.com/store/apps/details?id=com.delphicoder.flud for implementation reference.

**Comment by proninyaroslav** [comment]
@coolamz 
I think we need to port this feature from FrostWire. I also look at the implementation in Flud.

**Comment by coolamz** [comment]
How to do it?

**Comment by proninyaroslav** [comment]
@coolamz 
Port this class https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/AndroidPlatform.java

**Comment by coolamz** [comment]
Please tell me stel by step procedure. 
 since I'm newbie.

**Comment by proninyaroslav** [comment]
@coolamz 
Nobody will be able to describe to you the entire procedure step by step, as this kind of experiment, not a trivial procedure. Moreover, this class used in FrostWire with excess code that we do not fit.

**Comment by coolamz** [comment]
Okay! Thanks for the help! Would like to know resources from which I can learn. Plz reply with links. You can see my app in playstore : https://play.google.com/store/apps/details?id=amey.com.voicebutton

I'll add more features into this client and publish it soon.

**Comment by proninyaroslav** [comment]
@coolamz 
http://www.libtorrent.org/, https://github.com/frostwire/frostwire-jlibtorrent/ (you can generate javadoc files), https://developer.android.com/guide/topics/providers/document-provider.html (our main problem for 4.4 and higher)

**Comment by coolamz** [comment]
Thank you so much! Will follow!

**Comment by proninyaroslav** [comment]
You can see this problem https://github.com/frostwire/frostwire-jlibtorrent/issues/132

**Comment by mianharisali** [comment]
@proninyaroslav  we tried porting lolipopplatform , but so far we are failed, tried to add the wrapper in libtorrent but when we launched the app , it pauses the torrent and do not create any file in it.

**Comment by proninyaroslav** [comment]
I think it would be a difficult task, the authors frostwire talk about it. I think to see how it is implemented in flud.

**Comment by mianharisali** [comment]
@proninyaroslav if we use the code from frostwire like lolipopfilesystem , i dnt think it will be difficult.
the only use of that class is in setting the posix wrapper , we are testing and following the frost wire code , but so far failed , really cant understand where we are wrong.
can you give some information about flud? is it torrent cliend using jlibttorrent?

**Comment by proninyaroslav** [comment]
@mianharisali 
flud is non-free torrent client, but it uses libtorrent library. As far as I know, before this client also suffered from this problem, but now they were able to circumvent (rumored).

**Comment by proninyaroslav** [comment]
I looked implementation support downloading to external storage in Flud. The mechanism is very simple: as a directory to download uses app directory. I doubt that it is convenient, but it is the only adequate solution.

**Comment by Nutomic** [comment]
One thing you can easily do is use [Context.getExternalFilesDirs()](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDirs(java.lang.String)).

**Comment by proninyaroslav** [comment]
@Nutomic 
Yes, I know about this feature. The main question: is how much it's convenient for users?

**Comment by Nutomic** [comment]
I think it would be very useful for people who don't have any space don't heir primary sdcard. I think its a good workaround, better than nothing.

**Comment by proninyaroslav** [comment]
@Nutomic 
Ok, I'll do it in the coming days.

**Comment by yilmzfurkan** [comment]
@proninyaroslav thanks! This is the only thing that keeps me away from Libretorrent. I don't have any space on my internal storage. :( Never thought i would change Flud but your app is awesome and uses the material design so good!

**Comment by fidelc** [comment]
@proninyaroslav Thank you. This is literally the only reason why I'm still using Flud instead of libretorrent

**Comment by proninyaroslav** [comment]
Due to lack of time I delayed commit publishing, but now everything is ok. For devices with Android 4.4 and later download to the external storage is limited this folder `/storage_path/Android/data/org.proninyaroslav.libretorrent/`

**Comment by raztd** [comment]
Could this be implemented using the Android 5's Storage Access Framework API [1] ?
Seems this was the solution used by Open Camera [2]
[1]  https://developer.android.com/guide/topics/providers/document-provider.html
https://stackoverflow.com/questions/36862675/android-sd-card-write-permission-using-saf-storage-access-framework
[2] https://github.com/almalence/OpenCamera/

**Comment by proninyaroslav** [comment]
@raztd 
You can see about SAF here https://github.com/frostwire/frostwire-jlibtorrent/issues/132

**Comment by Pidus** [comment]
External storage is supported but limited this folder: /storage_path/Android/data/org.proninyaroslav.libretorrent/
But it would be more convenient if we could choose a different folder. Flud supports this. And this manga reader app supports this too: https://github.com/inorichi/tachiyomi

**Comment by proninyaroslav** [comment]
@Pidus Thanks, I'll see it. Everything will depend on how well it fits into the current app architecture.

**Comment by jeanbruder** [comment]
External storage is not shown in the storage list, how to fix this please ?

**Comment by proninyaroslav** [comment]
@jeanbruder what model of your device? is this a SD card?

**Comment by jeanbruder** [comment]
@proninyaroslav : Yes, external SD card. Can't we imagine acquire root privileges if available (my phone is rooted). Thx.

**Comment by proninyaroslav** [comment]
@jeanbruder support for external storage is not ideal, it will be rethought.

**Comment by proninyaroslav** [comment]
I did some code that works with Storage Access Control, but there is one problem: I can't get path to the external storage that does not have a UUID, and without path `libtorrent` lib can not work with the file system. That is, this makes this function inadequate for many external storages (e.g USB flash) and even for many SD cards.
