### ISSUE TITLE
Icon rather similar to Syncthing's

### ISSUE THREAD

**Issue by JohnVeness** [proninyaroslav/libretorrent#50]
I realise there are only so many different icons that can be created, but the current icon for your app is rather similar to Syncthing's (see e.g. https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid) so if a user has both LibreTorrent and Syncthing installed, there is a slight confusion.

**Comment by proninyaroslav** [comment]
Hello. I've heard about it. I didn't copy logo, it's my fantasy. I was surprised when I discovered a similar logo, since I have not heard about this application. If you offer the best version of the logo, I will consider it.

**Comment by JohnVeness** [comment]
Oh, I wasn't suggesting you had copied it, I think it's just one of things where two people came up with a similar idea. I'm afraid I'm not an artist so cannot create an alternative logo, but maybe someone else can come up with one.

**Comment by igor-dyatlov** [comment]
@proninyaroslav Maybe you have requirements and wishes to the icon?
