### ISSUE TITLE
Not always shows progress of checking

### ISSUE THREAD

**Issue by teod0r** [proninyaroslav/libretorrent#51]
It not always shows progress of checking consistency of a torrent.

**Comment by proninyaroslav** [comment]
Hello. What do you mean by checking progress?

**Comment by teod0r** [comment]
Checking of what  have been downloaded. After the program crashed it checks the consistency of torrent.
By checking progress I mean scale and percents, which aren't always shown.

**Comment by proninyaroslav** [comment]
Can you attach screenshot with this problem? Error itself is also desirable, after which it occurs.

**Comment by proninyaroslav** [comment]
if this problem appears again, let me know.
