### ISSUE TITLE
Immediately pauses download

### ISSUE THREAD

**Issue by ZerataX** [proninyaroslav/libretorrent#52]
As soon as I try to resume a download it immediately pauses again.
I've tried to force recheck, but after it's done it pauses again.
My phone is the oneplus one with custom rom DirtyUnicorns.

 ![libretorrent.gif](https://jii.moe/4JIhyhWMz.gif)

**Comment by proninyaroslav** [comment]
Hello. You can see this problem in #39. Please install this version https://proninyaroslav.ru/ftp/app-release.apk (it's a current master branch, updated to jlibtorrent 1.2.x) and check it.

**Comment by ZerataX** [comment]
I wasn't exactly sure if it's the same problem, because for me I couldn't resume the download at all, but this version seems to fix it anyways, thank you very much.
