### ISSUE TITLE
New launcher and notification icons

### ISSUE THREAD

**Issue by igor-dyatlov** [proninyaroslav/libretorrent#56]
I propose a redesign of icons. Fixed [color](https://material.google.com/style/color.html#color-color-palette) launcher icons on purple 500 (**#9C27B0**) and a figure closer to the [guideline](https://material.google.com/style/icons.html#icons-system-icons).
Also changed the notification icon under the styling system.
It is also possible to arrange the vote for the selection of icons.
[ic_launcher.zip](https://github.com/proninyaroslav/libretorrent/files/624847/ic_launcher.zip)
[ic_app_notification.zip](https://github.com/proninyaroslav/libretorrent/files/624848/ic_app_notification.zip)

**Comment by proninyaroslav** [comment]
Yes, I think we need to arrange a vote. Logo redesign has been proposed previously #50

**Comment by igor-dyatlov** [comment]
@proninyaroslav This topic was to close? And to continue the discussion in #50 ?

**Comment by proninyaroslav** [comment]
@igor-dyatlov 
I think to open special issue for vote and close these.

**Comment by proninyaroslav** [comment]
@igor-dyatlov 
You will create issue? Then I ask you to add two logo for comparisons (old and new) and attach your logo source.

**Comment by igor-dyatlov** [comment]
@proninyaroslav Yes, I will create a issue.
