### ISSUE TITLE
Voting for a new launcher icon

### ISSUE THREAD

**Issue by igor-dyatlov** [proninyaroslav/libretorrent#57]
I propose a redesign of icons. Icons need individuality, awareness. 

**Requirements**

- [Geometry](https://material.google.com/style/icons.html#): Circle

- [Color](https://material.google.com/style/color.html#color-color-palette): purple 500 (**#9C27B0**)

His proposal to attach comments. Overlooking before/after.

![ic_launcher](https://cloud.githubusercontent.com/assets/15961107/20800077/3e13855c-b7f5-11e6-83bb-5cf15d201c9d.png) / ![ic_launcher](https://cloud.githubusercontent.com/assets/15961107/20800086/4f052cbc-b7f5-11e6-8d46-20a084afda6e.png)

**Comment by Nutomic** [comment]
Btw the icon looks very similar to [Syncthing's](https://syncthing.net/). Not saying that's a problem, but it might be confusing for users.

**Comment by Cormak** [comment]
The after is not very good looking. The white lines are too thick and the shape looks odd.

**Comment by igor-dyatlov** [comment]
@proninyaroslav @Cormak What shape would you like to see?

**Comment by Salamandar** [comment]
Actually I like the current icon. The color is all its individuality and the shape is correct.

**Comment by Cormak** [comment]
@igor-dyatlov I actually think the icon we have is fine. It's unique enough not to be confused with Syncthing's icon. The proposed icon was actually worse than the original. Unless we get a suggestion that is actually better, I don't see any need to change it.

**Comment by proninyaroslav** [comment]
I think that at the moment this issue is not so significant. If it's still relevant, let me know.
