### ISSUE TITLE
QR and barcode support

### ISSUE THREAD

**Issue by zhangle1** [proninyaroslav/libretorrent#62]
This App is very cool, can not provide support for the next two dimensional code scanning, online video playback

**Comment by proninyaroslav** [comment]
Hello. Streaming support (including video) already discussed here #19. What do you mean by scanning the two-dimensional code?

**Comment by zhangle1** [comment]
Two dimensional code scanning to obtain the magnetic link string or more..Maybe I think it's troublesome to copy from somewhere else.
