### ISSUE TITLE
App is showing wrong download directory size

### ISSUE THREAD

**Issue by hieu-van** [proninyaroslav/libretorrent#63]
Hello,

I'm using LibreTorrent 1.1. It is a really great torrent client, in my opinion. But I've got an annoying problem recently:

My external SD card is mounted on /storage/sdcard1. It has about 5 GB free space. But when I changed the download directory to that, the app showed the free space was only about ~100 MB.

This bug makes downloading big file very unconvenient, as I have to download on PC, or use another torrent client...

Please fix asap!

**Comment by proninyaroslav** [comment]
This problem has been fixed in 1.2 (see #26). Please update and check it. Please let us know if this problem persists.

**Comment by proninyaroslav** [comment]
if this problem appears again, let me know.
