### ISSUE TITLE
Allow the user to move the application to adoptable storage

### ISSUE THREAD

**Issue by rohand7** [proninyaroslav/libretorrent#64]

**Comment by proninyaroslav** [comment]
Hello. Can you describe in detail your problem?

**Comment by rohand7** [comment]
Currently their is no option to move the application to adoptable storage like 
![This app's storage can be changed](https://cloud.githubusercontent.com/assets/12265908/21537818/fcd02de8-cdbb-11e6-9dbd-4d62dd5be37f.png)
![LibreTorrent does not have any option to change the storage like the following](https://cloud.githubusercontent.com/assets/12265908/21537814/f8a8031c-cdbb-11e6-93cd-d5be8a21adc3.png)

**Comment by proninyaroslav** [comment]
@rohand7 
Please install and check feature http://s000.tinyupload.com/?file_id=07377290171109539341

**Comment by proninyaroslav** [comment]
Due with 1.4 release, I close this issue, but if this problem appears again, let me know.
