### ISSUE TITLE
Crash at Peer Info Screen

### ISSUE THREAD

**Issue by mianharisali** [proninyaroslav/libretorrent#68]
Sometimes this app crashes on Peer information scree randomly.

**Comment by proninyaroslav** [comment]
Hello. Can you provide a log with an error?

**Comment by mianharisali** [comment]
@https://github.com/frostwire/frostwire-jlibtorrent/issues/144

please take a look at this issue , this is causing your app to crash.

**Comment by proninyaroslav** [comment]
Error points a native code library, the app has nothing to do with it. Besides, I have never encountered this error.

**Comment by uchchishta** [comment]
This happens to me when downloading a large file, like 4GB. And all  the downloaded block files get deleted when it crashes :( (size falls back to where you paused at past)
I've set maximum connections to 50

**Comment by proninyaroslav** [comment]
@uchchishta 
Crash at peer info screen?

**Comment by uchchishta** [comment]
@proninyaroslav yes, it will ultimately crash even if you browse away to other tabs soon.

**Comment by proninyaroslav** [comment]
Due with 1.4 release, I close this issue, but if this problem appears again, let me know.
