### ISSUE TITLE
Peer ID?

### ISSUE THREAD

**Issue by the-researcher** [proninyaroslav/libretorrent#7]
Hello @proninyaroslav !

What is the peer ID for this program? If you don't assign a peer ID for the client, how is it derived from the frostwire-jlibtorrent library?

This is very tempting to use when combined with newer always-on Android boxes.

Thanks,

the_researcher

**Comment by Cormak** [comment]
I hope the dev makes it simply "LibreTorrent [version number]"

**Comment by proninyaroslav** [comment]
Default peer id of `libtorrent` is `LT`. If I make my peer id, it doesn't have to coincide with the existing ids, including with `libtorrent` id. But since the name of program is consonant with the name of `libtorrent`, I leave as is.
