### ISSUE TITLE
Maximum active downloads not working

### ISSUE THREAD

**Issue by noughtmare** [proninyaroslav/libretorrent#72]
I have set my maximum active downloads to 1, but libretorrent is still downloading 2 torrents at the same time.

**Comment by proninyaroslav** [comment]
Hello. I will check it.

**Comment by noughtmare** [comment]
I restarted libretorrent and it worked. So I guess a restart is needed for the setting to take effect.

**Comment by proninyaroslav** [comment]
Thank you. This will be fixed in the next version.

**Comment by proninyaroslav** [comment]
Fixed.
