### ISSUE TITLE
torrent like ubuntu one starts and then gets stuck

### ISSUE THREAD

**Issue by alex9099** [proninyaroslav/libretorrent#75]
Hi. When i try to download a torrent it starts at like 200kbs and then gets stuck

I dont know what else can i say to help solve the problem :/

**Comment by proninyaroslav** [comment]
Hello. In most cases, it speaks of the fact that the seeders haven't all pieces of this torrent, so it downloads only available pieces. Try to verify this by downloading another torrent.

**Comment by alex9099** [comment]
I dont think thats the problem... it seems like libretorrent wont write to the sd card :/

**Comment by proninyaroslav** [comment]
Have you updated to 1.3?

**Comment by alex9099** [comment]
It is not released yet on fdroid. Where can i get it? Compiling it?

**Comment by proninyaroslav** [comment]
Sometimes on the release page download broken APK. Release on F-Droid should soon occur, since commit with changes in the F-Droid repository was adopted 2 days ago.

**Comment by alex9099** [comment]
the 1.3 version says permission denied and i there is only internal storage on the droplist

**Comment by proninyaroslav** [comment]
Do you have a SD card? Can you write the full path to the card?

**Comment by alex9099** [comment]
Yes i have, were can i write it? if you mean here it is /storage/sdcard1

**Comment by proninyaroslav** [comment]
What version of android? If version is below 4.4 then recording on the SD card should take place without problems.

**Comment by alex9099** [comment]
5.1 or 5.0.1, not sure :/

**Comment by alex9099** [comment]
@proninyaroslav ?

**Comment by proninyaroslav** [comment]
Hi. I checked SD card on 5.1 and not found problems
![screenshot_2017-04-07-11-33-46](https://cloud.githubusercontent.com/assets/7840559/24793189/c3982a6e-1b89-11e7-8503-7aafe853db94.png) ![screenshot_2017-04-07-11-33-54](https://cloud.githubusercontent.com/assets/7840559/24793190/c399aa7e-1b89-11e7-9433-483c8d90c86f.png)

**Comment by alex9099** [comment]
Does the app need to be moved to sd card? that folder seems to be the app reserved folder, not the sdcard root :/

**Comment by proninyaroslav** [comment]
You don't need to move app. This folder appears automatically and since 4.4 app can write data only to it. About it see https://github.com/proninyaroslav/libretorrent/issues/5

**Comment by alex9099** [comment]
:/ but it only shows to me Internal Storage (500MB) /storage/emulated/0


I dont have any Android folder on the SD card :/

**Comment by proninyaroslav** [comment]
I don't know how to help you. This is a very strange behavior, because to get the storages list I use standard Android tools. What is the model of your device?

**Comment by alex9099** [comment]
It is a BQ Aquaris E5 FHD (codename vegetafhd) it is from a spanish brand :)

It has a mediatek processor, the ROM that i'm using is "kind" of oficial, because mediatek did not release some sources to do the official lolipop ROM, so the manufacturer just released a beta to anyone who wanted to use lolipop :)

**Comment by proninyaroslav** [comment]
I think the problem is just this. I don't have this device and it will be difficult for me to study it. It is likely they use some non-standard things. Are there any other apps that don't see SD card?

**Comment by alex9099** [comment]
Nope, all other apps that i have can read/write on the sd card (VLC, Amaze/ES File Explorer, and some others that i am not remembering now :/)

**Comment by proninyaroslav** [comment]
And other torrent clients?

**Comment by alex9099** [comment]
have not tried, can you give me some examples?

**Comment by proninyaroslav** [comment]
E.g Flud, it has a similar method of obtaining a SD cards list.

**Comment by alex9099** [comment]
Flud also dont work :/ it says that the internal memory is the External one, if i navigate to the external SD it says that it is not writable :/

**Comment by proninyaroslav** [comment]
Perhaps it remains to wait for fix in the firmware.

**Comment by alex9099** [comment]
Hum, so if it is a firmware issue i have to buy a new phone because this one stoped being supported :/

It's sad :( Well, meanwhile i'll just move most of the things i have on the internal memory to the SD and then download to the internal memory :D 
Closing this for now

**Comment by alex9099** [comment]
it seems like this client works fine on writting files to sd, take a look @proninyaroslav

**Comment by alex9099** [comment]
I forgot the link....

https://gitlab.com/axet/android-torrent-client/tree/HEAD

**Comment by proninyaroslav** [comment]
Ok, I will take a look.

**Comment by proninyaroslav** [comment]
Version 1.5 is out, in case of repeat this problem reopen the issue.
