### ISSUE TITLE
Trackers aren't parsed

### ISSUE THREAD

**Issue by gjedeer** [proninyaroslav/libretorrent#76]
I was downloading this torrent file: https://stealthisshow.com/wp-content/plugins/podcast-to-torrent/torrents/f8e5a0836aca6b54f2e7d5bbdef1b3d8.torrent

In LibreTorrent I could not get it to start, the Trackers tab was just showing dht/lsd/pex and no peers were found.

I opened that file in Flud too, to discover that it had 3 trackers and quickly found peers.

**Comment by proninyaroslav** [comment]
Hi. I don't observe the problem. I think it was a problem on the side of tracker.

![screenshot_20170318-122159](https://cloud.githubusercontent.com/assets/7840559/24070865/49455844-0bd6-11e7-8707-a9c0170012b6.png)

**Comment by gjedeer** [comment]
Thank you for your super fast answer.

If there are trackers present in the Trackers tab, I'll close it. Maybe it's just DHT working better for you.

**Comment by proninyaroslav** [comment]
I have 3 trackers. If this problem repeats, reopen this issue.
