### ISSUE TITLE
Missing in the "List of free and open-source Android applications" on wiki

### ISSUE THREAD

**Issue by Maxim-Mazurok** [proninyaroslav/libretorrent#77]
Please, add this application to the [List of free and open-source Android applications](https://en.wikipedia.org/wiki/List_of_free_and_open-source_Android_applications) on Wikipedia. I think it's better that author add it by himself, so all data will be accurate and up to date. Thanks in advance!

**Comment by proninyaroslav** [comment]
Hello. Added, see General section.

**Comment by proninyaroslav** [comment]
Changes were rejected https://en.wikipedia.org/wiki/User_talk:Pronin_yaroslav#March_2017

**Comment by dessalines** [comment]
wtf, I'll get on there too.

**Comment by dessalines** [comment]
I reverted their deletion, and even though they complained, it seems like they're letting it stay.

**Comment by proninyaroslav** [comment]
Ok, thank you. I think that my changes were rejected because I'm developer of this app.
