### ISSUE TITLE
Sometimes torrents don't start

### ISSUE THREAD

**Issue by gedling** [proninyaroslav/libretorrent#78]
As title. For some reason some downloads will add as normal, will go to downloading and just not find any seeds even though there are hundreds available. Sometimes if I stop and add it again it will start the second time. Sometimes it will start working minutes later. Once it starts receiving data it works perfectly. This issue doesn't seem to be present on Flud or other Android torrent clients. I love your app and I love that it's open source but it just isn't working consistently for some reason. Still happening as of 1.3.

Thank you for all your hard work.

**Comment by proninyaroslav** [comment]
Hello. Thanks for the bugreport. I will report this to the developer of library, which I use in this application.

**Comment by gedling** [comment]
For what it's worth, running CM13 on a OnePlus 3. Has been an issue since the app first came out, so thought I'd bring it to your attention. Thank you for the prompt response!

**Comment by Cormak** [comment]
@proninyaroslav Any progress? Every minute that libretorrent doesn't work, the more potential users we drive away.

**Comment by proninyaroslav** [comment]
@Cormak I understand the whole complexity of the problem, but I'm not going to leave this project. At the moment I have little free time, but in the near future I will deal with this issue.

**Comment by proninyaroslav** [comment]
Main thread #79
