### ISSUE TITLE
Downloads remain at 0%

### ISSUE THREAD

**Issue by dar-irl** [proninyaroslav/libretorrent#79]
I'm experiencing an issue with LibreTorrent where none of my downloads are working. The torrent is added just fine, but after that everything stops -- the progress remains at 0%, it isn't connected to any peers, and it shows no upload/download activity.

I've tested this with multiple devices, torrents, and trackers, and I still get the same issue. For comparison, I used another torrent app from the Play Store and it worked as normal.

LibreTorrent ver. 1.3
Android ver. 7.0

For reference, here's a screenshot of the app when I try to download something. 

![screenshot_20170404-180153](https://cloud.githubusercontent.com/assets/18043024/24681170/028261ec-1962-11e7-9440-3d9f8ac5c841.png)
![screenshot_20170404-180429](https://cloud.githubusercontent.com/assets/18043024/24681171/0284ed4a-1962-11e7-82ec-a3cbc34aaca1.png)

**Comment by proninyaroslav** [comment]
Hello. Please send me link for testing.

**Comment by gedling** [comment]
Same issue I reported a few days ago. I don't think it's library related...

**Comment by DMSalesman** [comment]
Happens to me as well.

**Comment by proninyaroslav** [comment]
@DMSalesman @gedling 
It began to happen since 1.3?

**Comment by gedling** [comment]
It was happening before, to be honest. The inconsistent downloading was what forced me back to Flud. But I'd love to use LibreTorrent if it was only able to reliably start downloads every time. Sometimes it'll kick in after five minutes stuck at 0% or when stop and start again, but generally it's a stress and a hassle whereas Flud doesn't have that problem.

**Comment by proninyaroslav** [comment]
@gedling 
I will discuss this problem with the developer of the library, since the entire low-level infrastructure is located exactly in it, my task is only interact with the library's API.

**Comment by surferjoeit** [comment]
Hello, i have the same problem, but it started with 1.3. 1.2 was fine for me and i reinstalled  it.

**Comment by Cormak** [comment]
Also happening to me on 1.3. None of my downloads start.

I think it has to do with Android 7.1.1, I'd like to know what device the author uses and what version of Android he is running.

**Comment by dessalines** [comment]
This is a serious issue, I can't use libretorrent because none of my downloads will start.

**Comment by proninyaroslav** [comment]
In the near future, I will slightly rebuild app architecture and update main library to a new version. As far as I know, this problem has been fixed in it.

**Comment by Cormak** [comment]
@proninyaroslav Thank you for sticking to this project. It is the only open-source torrent client for Android and it should get as much attention as possible. I just wish you had more contributors to help you out.

**Comment by proninyaroslav** [comment]
Due with 1.4 release, I close this issue, but if this problem appears again, let me know.

**Comment by surferjoeit** [comment]
On my device it's seems that nothing changed. Torrent don't start, is always in pause.

**Comment by proninyaroslav** [comment]
@surferjoeit
Please try to delete and add again old torrens that's doesn't start. I checked on a lot of magnets and they all worked and downloaded.

**Comment by surferjoeit** [comment]
I just opened some new magnets.... no old torrents. And it doesn't work... or better only once i received notification of torrent download completion (and it was really completed) even if it never started according to main screen information... But just once...

**Comment by proninyaroslav** [comment]
This behaviour is observed only in this app and with all torrents?

**Comment by surferjoeit** [comment]
It's the only torrent app i have... I tried with 3 or 4 magnets and the behavior was the same, except for the only one completed i mentioned before. I can only try to download torrent files and open it with the app, just to see if the behavior is different..

**Comment by proninyaroslav** [comment]
Strange behaviour. This is a private trackers? I advise you to try to open these torrents in other programs, or try to download torrents from other trackers.

**Comment by surferjoeit** [comment]
How can i know if it's a private tracker? Anyway, i downloaded a torrent file and opened it with the app. It works. When i try to open a magnet it doesn't work.

**Comment by proninyaroslav** [comment]
It would be great if you sent me an example of the torrent that doesn't work for you.

**Comment by surferjoeit** [comment]
Hello, this Is a magnet not working.

magnet:?xt=urn:btih:af27ef40f5358a1ed2f6e8b726034dfe143d9f9f&dn=Urania%20Rivista%208&tr=udp%3a%2f%2ftracker.tntvillage.scambioetico.org%3a2710%2fannounce&tr=http%3a%2f%2ftracker.tntvillage.scambioetico.org%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fIPv6.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.mg64.net%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce

Sent from my WIKO RIDGE 4G

Il 14/lug/2017 16:07 Yaroslav Pronin <notifications@github.com> ha scritto:

**Comment by proninyaroslav** [comment]
Hmm, yes, initially pauses. I'll check it, maybe this problem in jlibtorrent library.

**Comment by proninyaroslav** [comment]
@surferjoeit 
New thread for this problem https://github.com/proninyaroslav/libretorrent/issues/93 .
