### ISSUE TITLE
Please allow ports higher than 9999

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#8]
In the settings - network - port menu, you can't type in a port greater than 9999, and the "random port" feature seems to restrict itself the same way.

According to torrent guides such as the Vuze wiki:

https://wiki.vuze.com/w/Select_port_for_Vuze

>Vuze needs only one port for the main data transfer functionality. Choose a port from the 49160–65534 range. If you really need to choose a port within the range 1024–49151 make sure you pick an "unassigned" port listed at the IANA port list and which is not already in use by some other application in your computer. 

This guide also recommends the same.  http://www.techsupportalert.com/content/optimizing-torrent-speed.htm

>The safest choice is a port in the 49160-65534 range as this will avoid ISP blocks and possible conflicts with other applications.

Please let us get to that port range, and please make the "random port" feature lets us get to that port range as well.

**Comment by proninyaroslav** [comment]
Thanks for the comment, it will be done.
