### ISSUE TITLE
Private torrents (trackers says "not working")

### ISSUE THREAD

**Issue by HarryPhoon** [proninyaroslav/libretorrent#81]
I added a torrent along with the torrent files to my tablet (Nexus 7 v2) and succesfully started seeding without downloading. But i can't seed because on the trackers list my tracker links say "Not working". The tracker is private.

**Comment by proninyaroslav** [comment]
Hello. Could you send a screenshot of this problem?

**Comment by HarryPhoon** [comment]
Sure
http://imgur.com/GnGaiu7
http://imgur.com/bVuReVS
http://imgur.com/5SDi0hI

**Comment by proninyaroslav** [comment]
I think this problem will be solved in the next release (after 1.4).

**Comment by proninyaroslav** [comment]
Please read official answer of `jlibtorrent` developer @aldenml:

> We don't support `HTTPS` trackers, we exclude any ssl support from `jlibtorrent` to save some space in the final binary (but still we use `libcrypto` for hash acceleration). Adding support in a custom build should be relatively easy, but not sure if worth the trouble, because HTTPS trackers does not provide any meaningful security.
Feel free to provide arguments if you think this feature is necessary.

**Comment by J-qak** [comment]
@HarryPhoon: CzTorrent PIDs are secret information, anyone can now download on your account. You posted it on the image on Imgur, it's part of tracker address, right after the question mark. You should reset your PID in CzTorrent account and manually update PIDs in your already downloaded torrents so you can seed them.

Anyway, changing tracker address from https to http usually solves the problem for me, at least on CzT.

**Comment by J-qak** [comment]
Update from `jlibtorrent` developer @aldenml:

> After discussing the issue internally, we decided to revisit it

**Comment by proninyaroslav** [comment]
Realised.
