### ISSUE TITLE
Can't change Save Directory

### ISSUE THREAD

**Issue by alabrand** [proninyaroslav/libretorrent#83]
Hello! There is a problem with LibreTorrent.

When I try to change save directory I get "Permission Denied".

**Comment by proninyaroslav** [comment]
Hello. Please provide Android version and the path to folder that you are trying to assign to save.

**Comment by arshamatonyan** [comment]
![libre torrent](https://cloud.githubusercontent.com/assets/9428627/26273190/a4603c94-3d3b-11e7-9e96-8c32ca7793f1.png)
this permission error was given then I press ".." to go back one level in directory.
it has happened on SONY TV android 6.0 and galaxy S6 android 7.0

**Comment by proninyaroslav** [comment]
That's right. On android 4.4 and above you can't select any storages other than those provided by the spoiler above (white arrow in the toolbar).

**Comment by proninyaroslav** [comment]
Due with 1.4 release, I close this issue, but if this problem appears again, let me know.
