### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by r9guy** [proninyaroslav/libretorrent#84]
on SONY BRAVIA TV android 6.0.1  the app doesn't have launcher  icon. it is possible though to open it from system->Apps menu.

**Comment by proninyaroslav** [comment]
Officially, LibreTorrent doesn't support Android TV, but I think that adding support will not be difficult.

**Comment by proninyaroslav** [comment]
Android TV support will be implemented later, because it requires a UI fully for TV format.
