### ISSUE TITLE
Add torrent dialog broken

### ISSUE THREAD

**Issue by arshamatonyan** [proninyaroslav/libretorrent#85]
![libre torrent](https://cloud.githubusercontent.com/assets/9428627/26273270/8af92908-3d3d-11e7-9a05-bab07227991e.png)

select torrent file and Libre torrent will kick in add torrent dialog. this is how it looks. really useless

**Comment by proninyaroslav** [comment]
Could you describe the whole situation in more detail? With such problems it's difficult to work, because they do not show themselves in the usual situation.

**Comment by arshamatonyan** [comment]
I have a torrent file. Then i open it in android. It is gandled by libre torrent. So it is assumed tjat libretorrent should show something in torrent adding dialog, but it shows nothing at all. This behavior apeared on Sony Android TV 6.0.1

**Comment by proninyaroslav** [comment]
Did you open file directly via the LibreTrent or from another app? Is this problem associated with only one torrent file or is it happening with all files? Do you use some optimization tools or tweaks on your phone?

**Comment by arshamatonyan** [comment]
I open the torrent file from file browser or chromes download files section.
All torrwnts behave the same way. On mobile phone though i noticed that after waiting some time , closing opening libretorrent it starts to work, but on android tv it never worked.
I dont ise any optimisation apps, also battery optimisations are disabled

**Comment by proninyaroslav** [comment]
Strange behavior, I try to deal with this in the next release. About support android tv I said earlier.

**Comment by arshamatonyan** [comment]
Thanks, well noted

**Comment by proninyaroslav** [comment]
Due with 1.4 release, I close this issue, but if this problem appears again, let me know.
