### ISSUE TITLE
Possibility of using Coverity Scan for code analysis?

### ISSUE THREAD

**Issue by popcornenthusiast** [proninyaroslav/libretorrent#86]
About Coverity:

> What is Coverity Scan?
> 
> Coverity Scan is a service by which Coverity provides the results of analysis on open source coding projects to open source code developers that have registered their products with Coverity Scan.
> 
> Coverity, the development testing leader, is the trusted standard for companies that need to protect their brands and bottom lines from software failures. Coverity Scan is powered by Coverity® Quality Advisor. Coverity Quality Advisor surfaces defects identified by the Coverity Static Analysis Verification Engine (Coverity SAVE®) for fast and easy remediation.
> 
> Coverity offers the results of the analysis completed by Coverity Quality Advisor on registered projects at no charge to registered open source developers.
> What is static analysis?
> 
> Static analysis is a set of processes for finding source code defects and vulnerabilities.
> 
> In static analysis, the code under examination is not executed. As a result, test cases and specially designed input datasets are not required. Examination for defects and vulnerabilities is not limited to the lines of code that are run during some number of executions of the code, but can include all lines of code in the codebase.
> 
> Additionally, Coverity's implementation of static analysis can follow all the possible paths of execution through source code (including interprocedurally) and find defects and vulnerabilities caused by the conjunction of statements that are not errors independent of each other. 

Source: https://scan.coverity.com/faq

LibreOffice's case of success after using Coverity:

> https://webcache.googleusercontent.com/search?q=cache:WD0hZEtvR2gJ:www.coverity.com/press-releases/libreoffice-improves-software-quality-coverity-scan/+&cd=2&hl=pt-BR&ct=clnk&gl=br&client=firefox-b
> 
> http://www.infoworld.com/article/2687117/open-source-software/libreoffice-code-ten-times-better-than-proprietary.html
> 
> http://www.ocsmag.com/2014/11/30/libreoffices-coverity-defect-density-is-0-00/

Coverity Scan: https://scan.coverity.com/

There is also SonarQube: https://sonarcloud.io/

**Comment by proninyaroslav** [comment]
Thanks, I will consider this possibility.

**Comment by popcornenthusiast** [comment]
@proninyaroslav Hi. Did you get any good results with Coverity or SonarQube?

**Comment by proninyaroslav** [comment]
I added the project in Coverity Scan and in the near future I will analyze.
