### ISSUE TITLE
Support USB Storage

### ISSUE THREAD

**Issue by Null-Senpai** [proninyaroslav/libretorrent#87]
Please add support for saving to external USB Storage (so those of us with only small internal storage can use USB OTG Adapter to connect USB Drive). 

_Sent from my Xiaomi Mi4c using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by proninyaroslav** [comment]
Hello. In the previous release, support for external devices was added, but that's all I can do for today. If device doesn't appear in the file manager list, it can't be used in the torrent client. About this problem see https://github.com/proninyaroslav/libretorrent/issues/5
