### ISSUE TITLE
Please allow us to change the theme to other colors

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#9]
Right now we only have the purple theme, but can we have the option to switch to other theme colors like blue, orange, red, green, etc?

A simple, small choice of colors would be nice, along with the ability to make them both dark and light.

**Comment by proninyaroslav** [comment]
I have already made issue #3 on this subject I'll do it as soon as I decide some problems (including support for external memory card and stick.

**Comment by hangduykhiem** [comment]
Wrong issue reference, sorry.

**Comment by proninyaroslav** [comment]
Material Dark theme is completed (see 11e9dda). It will be added in the next release.
About color switching: It will be a little more complicated, because code is badly swollen from it. I'll try to come up with a more elegant solution.

**Comment by tonkatsu313** [comment]
Is there a away to change the purple accent color? I cant stand this color. thx
