### ISSUE TITLE
Mixed download problems beginning in version 1.4

### ISSUE THREAD

**Issue by rak5381** [proninyaroslav/libretorrent#91]
When attempting to download only certain files from a torrent, I am able to assign priority as normal (including preading the save changes button).

However, when I leave the individual torrent interface, priorities change. 

Some files to which I have assigned a "normal" or "high" priority are changed to "low (ignore file)". And some files I have marked ignore begin downloading.

This happens whether I return to the torrent list interface (either with the app back arrow or the devices capacitave back button), or if I shut down the app in the notification bar and reopen.

The following actions within the specific torrent file interface do not cause this problem:  
*switching tabs (from "Files" to "Trackers" or "State" for example), 
*pausing and resuming the download, 
*"Force recheck", 
*"Enable sequential download", 
*switching to another app and returning to LibreTorrent

This problem began after upgrading from Version 1.3 to Version 1.4 from F-Droid.

**Comment by rak5381** [comment]
I experimented further.

The first thing I found was that setting a priority for an entire folder is honored.

Second, it appears as though setting certain files to "ignore" will set other files in the same folder to ignore, and sometimes not ignore the file selected.

For example, say a folder contains files: A, B, C, D, E, and F. And I want to ignore all files except C.

With all files set to "normal", and setting file B to "ignore", file E will be set to "ignore', file B may or may not be set to "ignore", and files A, C, D, E, and F may or may not remain "normal'.

However, manually setting file E to "ignore" will not necessarily effect file B.

Adjustments involve trial and error setting files to "ignore", and may require downloading several files I don't want in order to get those I do.

So it could be the case that in order to download file C, I need to set files A, C, and F to normal.

**Comment by proninyaroslav** [comment]
Thanks for the detailed description. I will consider this in the near future.

**Comment by proninyaroslav** [comment]
I fix this bug. Please check behaviour for correctness https://yadi.sk/d/OhyW92ZI3LAv3p

**Comment by rak5381** [comment]
Everything seems to be working fine.. Thank you.
