### ISSUE TITLE
Ability to save torrent file automatically

### ISSUE THREAD

**Issue by Pidus** [proninyaroslav/libretorrent#95]
It would be a good idea to have an option to copy/save the torrent files of added torrents (after resolving metadata). 
I like to backup the .torrent files of downloaded torrents.

**Comment by proninyaroslav** [comment]
Hello. This option already implemented

![screenshot_1500572058](https://user-images.githubusercontent.com/7840559/28430913-027c17ba-6d8b-11e7-8cfa-544d96a7e3bd.png)

You mean to automate this process and save torrents right after adding?

**Comment by Pidus** [comment]
Yes. An automated system would be great. 
For example, Flud has this option (Copy Torrent Files) under Storage. I didn't want to bring other apps into discussion but, this option would really be helpful. No other app (except Flud) has it.

**Comment by proninyaroslav** [comment]
Ok, it will be implemented in the nearest version.

**Comment by Pidus** [comment]
Thank you.

**Comment by proninyaroslav** [comment]
Added.
