### ISSUE TITLE
Some Play Store Related Suggestions 

### ISSUE THREAD

**Issue by Pidus** [proninyaroslav/libretorrent#96]
* Add this Github repository address in the app description in Play Store, so that curious people can get more information about this project without googling to find the address. 

* Add something like "OFFICIAL" in the app description to notify people that this is the legit app. There are already quite a few LibreTorrent clone in the store. And one of those even asking for money.

**Comment by proninyaroslav** [comment]
Link to GitHub is available in About dialog, but I can add in Play Store (if it doesn't violate rules).

**Comment by proninyaroslav** [comment]
Published.
