### ISSUE TITLE
Sequential Download only works if enabled while adding torrent

### ISSUE THREAD

**Issue by rak5381** [proninyaroslav/libretorrent#99]
If I add a torrent (with .torrent file or through a magnet link) and select "Enable Sequential Download", the torrent downloads in order.

But if I add a .torrent or magnet without selecting "Enable Sequential download", then try to enable it later, it doesn't work.

While in the torrent menu, it will let me check the box and press the save button. But though it stays checked, it doesn't download in order.

If I back out of the torrent menu to the download list page, then return to the torrent menu, the box is unchecked.

I'm using version 1.4, as linked in #91

**Comment by rak5381** [comment]
* without selecting "Enable Sequential download", then try to enable it later, it doesn't work.

While in the torrent menu, it will let me check the box and press the save button. But though it stays checked, it doesn't download in order.

If I back out of the torrent menu to the download list page, then return to the torrent menu, the box is unchecked.

**Comment by proninyaroslav** [comment]
Fixed, thanks.
